extends:
  - '@commitlint/config-conventional'
rules:
  type-enum:
    - 2
    - always
    - [chore, build, ci, docs, feat, fix, perf, refactor, revert, style, test, types, typings, tweak]
  subject-case:
    - 2
    - never
    - [start-case, pascal-case, upper-case]
  header-max-length:
    - 2
    - always
    - 72
